Code-4-Community/hands-across-the-sea-backend

- .travis.yml
- api/pom.xml
- common/pom.xml
- common/src/main/java/com/codeforcommunity/enums/Country.java
- common/src/main/resources/properties/server.properties.example
- persist/pom.xml
- persist/src/main/resources/db/migration/V1__Initial_Import.sql
- pom.xml
- service/pom.xml
- service/src/main/java/com/codeforcommunity/dataaccess/AuthDatabaseOperations.java
- Add V1 migration SQL script
- Update naming for HATS
> Initial HATS update

- api/src/main/java/com/codeforcommunity/dto/ApiDto.java
- api/src/main/java/com/codeforcommunity/dto/auth/ForgotPasswordRequest.java
- api/src/main/java/com/codeforcommunity/dto/auth/LoginRequest.java
- api/src/main/java/com/codeforcommunity/dto/auth/NewUserRequest.java
- api/src/main/java/com/codeforcommunity/dto/auth/ResetPasswordRequest.java
- api/src/main/java/com/codeforcommunity/rest/FailureHandler.java
- common/src/main/java/com/codeforcommunity/auth/Passwords.java
- common/src/main/java/com/codeforcommunity/enums/Country.java
- service/src/main/java/com/codeforcommunity/dataaccess/AuthDatabaseOperations.java
- service/src/main/java/com/codeforcommunity/processor/AuthProcessorImpl.java
Some changes to auth to allow users to sign up and log in
> Initial Auth Fix

- api/src/main/java/com/codeforcommunity/api/authenticated/IProtectedSchoolProcessor.java
- api/src/main/java/com/codeforcommunity/dto/report/ReportGeneric.java
- api/src/main/java/com/codeforcommunity/dto/report/ReportGenericListResponse.java
- api/src/main/java/com/codeforcommunity/dto/report/ReportWithLibrary.java
- api/src/main/java/com/codeforcommunity/dto/report/ReportWithLibraryInProgress.java
- api/src/main/java/com/codeforcommunity/dto/report/ReportWithoutLibrary.java
- api/src/main/java/com/codeforcommunity/dto/report/UpsertReportGeneric.java
- api/src/main/java/com/codeforcommunity/dto/report/UpsertReportInProgressLibrary.java
- api/src/main/java/com/codeforcommunity/dto/report/UpsertReportWithLibrary.java
- api/src/main/java/com/codeforcommunity/dto/report/UpsertReportWithoutLibrary.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/authenticated/ProtectedSchoolRouter.java
- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedSchoolProcessorImpl.java
- Update endpoint for updating school contacts to not return a json
- Update route for creating report for school with library (now at `/:school_id/reports/with-library`
- Add endpoint for getting paginated reports for a given school
- Fix some bugs with reports
> Add Route for Getting All Reports for One School

- api/src/main/java/com/codeforcommunity/api/authenticated/IProtectedUserProcessor.java
- api/src/main/java/com/codeforcommunity/dto/user/UserListResponse.java
- api/src/main/java/com/codeforcommunity/rest/RestFunctions.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/authenticated/ProtectedUserRouter.java
- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedUserProcessorImpl.java
- API Route is /user/?country=<name of country>
- The country query parameter is optional so route could also be /user/
> Gets list of users. Use this PR to get list of users. Ignore previous pr

- api/src/main/java/com/codeforcommunity/api/authenticated/IProtectedSchoolProcessor.java
- api/src/main/java/com/codeforcommunity/dto/school/BookLog.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/authenticated/ProtectedSchoolRouter.java
- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedSchoolProcessorImpl.java
Was missing a get book ID method
> Added book log id to response

- api/src/main/java/com/codeforcommunity/dto/report/ReportGenericListResponse.java
- api/src/main/java/com/codeforcommunity/dto/school/BookLogListResponse.java
- api/src/main/java/com/codeforcommunity/dto/school/SchoolContactListResponse.java
- api/src/main/java/com/codeforcommunity/dto/school/SchoolListResponse.java
Verified that all the DTO's had fields that can hold a value of null without throwing an exception.
> Verified DTO fields

- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedUserProcessorImpl.java
- Fix `GET` route `/user/data` so that `privilegeLevel` is not returned as `null`
> Fix user data response

- api/src/main/java/com/codeforcommunity/dto/school/School.java
- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedSchoolProcessorImpl.java
Removes a school contact value from the response because a school contact route already exists
> Removed contacts from response

- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedSchoolProcessorImpl.java
Reverts some fixes that remove build warnings that inadvertently broke JOOQ (yikes)
> revert jooq changes

- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedSchoolProcessorImpl.java
> Fix Reported Schools Endpoint

- common/src/main/java/com/codeforcommunity/enums/TimeRole.java
-Allows for the none value to be passed in the assigned person role field.
- Added the none field to the TimeRole enum.
> updated time role none value

- api/src/main/java/com/codeforcommunity/api/authenticated/IProtectedUserProcessor.java
- api/src/main/java/com/codeforcommunity/dto/user/UserDataResponse.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/authenticated/ProtectedUserRouter.java
- persist/src/main/resources/db/migration/V2_1__User_Disabled_Field.sql
- service/src/main/java/com/codeforcommunity/dataaccess/AuthDatabaseOperations.java
- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedSchoolProcessorImpl.java
- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedUserProcessorImpl.java
This PR addresses a few backend changes. It adds user id's to user responses, updated the DB with a column for a user disabled field, and adds the ability for an admin to disable a user account.
> Updated user routes

- api/src/main/java/com/codeforcommunity/dto/user/UserDataRequest.java
- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedUserProcessorImpl.java
> Added fields

- api/src/main/java/com/codeforcommunity/api/authenticated/IProtectedUserProcessor.java
- api/src/main/java/com/codeforcommunity/dto/user/UserDataResponse.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/authenticated/ProtectedUserRouter.java
- service/src/main/java/com/codeforcommunity/dataaccess/AuthDatabaseOperations.java
- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedUserProcessorImpl.java
[Ticket #1](https://code4community-team.monday.com/boards/866744728/pulses/1479253733)
[Ticket #2](https://code4community-team.monday.com/boards/866744728/pulses/1479263569)
Added routes to re-enable a disabled user and query for disabled users
New Routes Added
> Updated routes for re-enabling a user and querying for disabled users

- api/src/main/java/com/codeforcommunity/dto/report/ReportGeneric.java
- api/src/main/java/com/codeforcommunity/dto/report/ReportWithLibrary.java
- api/src/main/java/com/codeforcommunity/dto/report/ReportWithoutLibrary.java
- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedSchoolProcessorImpl.java
[associated ticket](https://code4community-team.monday.com/boards/866744728/pulses/1500401148)
Adds user name and school name to dto
Adds user name and school name to dto
> added user name and school name to report dto

- api/src/main/java/com/codeforcommunity/dto/auth/NewUserRequest.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/authenticated/ProtectedSchoolRouter.java
- common/src/main/java/com/codeforcommunity/auth/JWTData.java
- common/src/main/java/com/codeforcommunity/auth/JWTHandler.java
- common/src/main/java/com/codeforcommunity/enums/PrivilegeLevel.java
- persist/src/main/resources/db/migration/V2_4__Update_Privilege_Level.sql
- service/src/main/java/com/codeforcommunity/dataaccess/AuthDatabaseOperations.java
- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedSchoolProcessorImpl.java
- service/src/test/java/com/codeforcommunity/processor/ProtectedSchoolProcessorImplTest.java
Remove `STANDARD` and add `OFFICER` and `VOLUNTEER`.
This also makes `privilegeLevel` a required field for creating new users.
> Update User Privilege Level

- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedSchoolProcessorImpl.java
> Fixed invalid shipment year

- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedSchoolProcessorImpl.java
This PR fixes a bug where only an admin can update the reports of a library. This PR removes that admin check.
- Remove the barrier of having to be an admin to update reports
> Updated admin priviledge for updating reports

- pom.xml
> Log4J Bump

- api/src/main/java/com/codeforcommunity/api/authenticated/IProtectedDataProcessor.java
- api/src/main/java/com/codeforcommunity/dto/data/MetricGeneric.java
- api/src/main/java/com/codeforcommunity/dto/data/MetricsCountryResponse.java
- api/src/main/java/com/codeforcommunity/dto/data/MetricsSchoolResponse.java
- api/src/main/java/com/codeforcommunity/dto/data/MetricsTotalResponse.java
- api/src/main/java/com/codeforcommunity/dto/report/ReportWithoutLibrary.java
- api/src/main/java/com/codeforcommunity/dto/report/UpsertReportWithoutLibrary.java
- api/src/main/java/com/codeforcommunity/rest/ApiRouter.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/authenticated/ProtectedDataRouter.java
- common/src/main/java/com/codeforcommunity/enums/Country.java
- service/src/main/java/com/codeforcommunity/ServiceMain.java
- service/src/main/java/com/codeforcommunity/dataaccess/SchoolDatabaseOperations.java
- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedDataProcessorImpl.java
- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedSchoolProcessorImpl.java
> Jt data merging

- api/src/main/java/com/codeforcommunity/api/authenticated/IProtectedBookLogProcessor.java
- api/src/main/java/com/codeforcommunity/api/authenticated/IProtectedReportProcessor.java
- api/src/main/java/com/codeforcommunity/api/authenticated/IProtectedSchoolProcessor.java
- api/src/main/java/com/codeforcommunity/rest/ApiRouter.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/authenticated/ProtectedSchoolRouter.java
- service/src/main/java/com/codeforcommunity/ServiceMain.java
- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedBookLogProcessorImpl.java
- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedReportProcessorImpl.java
- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedSchoolProcessorImpl.java
- service/src/main/java/com/codeforcommunity/util/ProcessorUtility.java
This PR separates the reports and book log logic from the school processor into their own processor.
- Remove book log logic from school processor
- Remove report logic from school processor
- create school processor
- create report processor
> Fixed the refactor

- api/src/main/java/com/codeforcommunity/api/authenticated/IProtectedSchoolProcessor.java
- api/src/main/java/com/codeforcommunity/rest/ApiRouter.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/authenticated/ProtectedSchoolRouter.java
- service/src/main/java/com/codeforcommunity/ServiceMain.java
- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedBookLogProcessorImpl.java
- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedReportProcessorImpl.java
- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedSchoolProcessorImpl.java
- service/src/main/java/com/codeforcommunity/util/ProcessorUtility.java
> Fixed build errors

- api/src/main/java/com/codeforcommunity/api/authenticated/IProtectedSchoolProcessor.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/authenticated/ProtectedSchoolRouter.java
- common/src/main/java/com/codeforcommunity/auth/JWTData.java
- common/src/main/java/com/codeforcommunity/auth/JWTHandler.java
- service/src/main/java/com/codeforcommunity/dataaccess/AuthDatabaseOperations.java
- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedReportProcessorImpl.java
- service/src/main/java/com/codeforcommunity/processor/authenticated/ProtectedSchoolProcessorImpl.java
> Viewing form implementation across priviledge levels

- common/src/main/java/com/codeforcommunity/email/EmailOperations.java
> Updated logging to identify email issues

- common/src/main/java/com/codeforcommunity/email/EmailOperations.java
> Forced send emails to be true

- .github/workflows/deploy.yml
- common/src/main/java/com/codeforcommunity/email/EmailOperations.java
> Updated deploy yaml file

- .github/workflows/deploy.yml
Modifies deploy action to push docker image to private ECR, rather than deploy to ELB directly
> Update deploy.yml for ECR
